spring.application.name=Profesor
server.port=${PORT:8089}

# Eureka Server
eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Base de Datos (MIGRADO A POSTGRESQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/db_profesor}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# JPA / Hibernate (CORREGIDO A POSTGRESQL)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.duoc.Profesor=INFO
logging.file.name=logs/escuela.log

# Seguridad JWT
app.jwt.secret=${JWT_SECRET:clave-super-secreta-12345678901234567890}
app.jwt.expiration-ms=86400000

# Documentación Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.default-produces-media-type=application/hal+json